### PR TITLE
added c# porting of lz77

### PR DESCRIPTION
**Pull request by gitPhate**
Hello, I added a C# porting of the LZ77 algorithm, as I ported the java implementation for a project of mine. My implementation works on bytes.

### CODE REVIEW

**Comment by olle** [comment]
Hi, looks great. I'd love to pull this into the repo.

How about adding a small test, though? Also, any pointers on how to get such tests also running with the Mono-SDK would be super.

Thanks!

**Comment by gitPhate** [comment]
I have to worry you about the performance, I'm currently working to make it
quicker, and I'll add some tests. We'll stay in touch
Il 04/nov/2015 10:39 PM, "Olle Törnström" <notifications@github.com> ha
scritto:

**Comment by gitPhate** [comment]
Updates: I found the issue, in these days I will make another pull request with the right class. As for the mono tests, I never used it but I think that the test methods are the same as visual studios. I will post them in the new pull request, but consider that I don't have pretty much time (I'm at work and I develop only when I have nothing else to do).
I'll be in touch!

**Comment by olle** [comment]
Hi, sounds great. And regarding the tests/Mono - don't worry, it's all good.

I'll pull and merge when you're done. Thanks again!

**Pull request closed without merging**
